# -*- coding: utf-8 -*-
# Copyright 2023 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the ios_class_maps module
"""


class Class_mapsArgs(object):  # pylint: disable=R0903
    """The arg spec for the ios_class_maps module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "name": {"required": True, "type": "str"},
                "match_type": {
                    "default": "match-all",
                    "type": "str",
                    "choices": ["match-all", "match-any"],
                },
                "description": {"type": "str"},
                "class_type": {
                    "type": "str",
                    "default": "standard",
                    "choices": ["access-control", "stack", "standard"],
                },
                "matches": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "access_group": {
                            "type": "dict",
                            "mutually_exclusive": [["name", "number"]],
                            "options": {
                                "name": {"type": "str"},
                                "number": {"type": "int"},
                            },
                        },
                        "any": {"type": "bool"},
                        "application": {
                            "type": "dict",
                            "mutually_exclusive": [
                                ["source", "vendor", "version"]
                            ],
                            "options": {
                                "name": {"type": "str", "required": True},
                                "source": {
                                    "type": "str",
                                    "choices": [
                                        "cli",
                                        "cube",
                                        "msp",
                                        "nbar",
                                        "rfmd",
                                        "rsvp",
                                        "cac",
                                    ],
                                },
                                "vendor": {"type": "str"},
                                "version": {"type": "str"},
                            },
                        },
                        "application_attribute": {
                            "type": "dict",
                            "mutually_exclusive": [
                                [
                                    "category",
                                    "device_class",
                                    "media_type",
                                    "sub_category",
                                    "tcl",
                                ]
                            ],
                            "options": {
                                "category": {
                                    "type": "str",
                                    "choices": [
                                        "business-and-productivity-tools",
                                        "physical-security",
                                        "voice-and-video",
                                    ],
                                },
                                "device_class": {
                                    "type": "str",
                                    "choices": [
                                        "desktop-conferencing",
                                        "desktop-virtualization",
                                        "physical-phone",
                                        "room-conferencing",
                                        "software-phone",
                                        "surveillance",
                                    ],
                                },
                                "media_type": {
                                    "type": "str",
                                    "choices": [
                                        "audio",
                                        "audio-video",
                                        "control",
                                        "data",
                                        "video",
                                    ],
                                },
                                "sub_category": {
                                    "type": "str",
                                    "choices": [
                                        "control-and-signaling",
                                        "remote-access-terminal",
                                        "video-surveillance",
                                        "voice-video-chat-collaboration",
                                    ],
                                },
                                "tcl": {"type": "str"},
                            },
                        },
                        "application_group": {
                            "type": "str",
                            "choices": [
                                "telepresence-group",
                                "vmware-group",
                                "webex-group",
                            ],
                        },
                        "cac_status": {
                            "type": "str",
                            "choices": ["admitted", "un-admitted"],
                        },
                        "class_map": {"type": "str"},
                        "cos": {"type": "list", "elements": "int"},
                        "cos_inner": {"type": "list", "elements": "int"},
                        "destination_mac_address": {"type": "str"},
                        "discard_class": {"type": "int"},
                        "dscp": {
                            "type": "dict",
                            "options": {
                                "dscp_values": {
                                    "type": "list",
                                    "required": True,
                                    "elements": "int",
                                },
                                "ip_versions": {
                                    "type": "str",
                                    "default": "IPv4-and-IPv6",
                                    "choices": ["IPv4-and-IPv6", "IPv4"],
                                },
                            },
                        },
                        "object_group_security": {
                            "type": "dict",
                            "options": {
                                "endpoint": {
                                    "type": "str",
                                    "required": True,
                                    "choices": ["destination", "source"],
                                },
                                "name": {"type": "str", "required": True},
                            },
                        },
                        "input_interface": {
                            "type": "dict",
                            "options": {
                                "interface_name": {
                                    "type": "str",
                                    "required": True,
                                    "choices": [
                                        "acr",
                                        "atm-acr",
                                        "analysis-module",
                                        "appnav-compress",
                                        "appnav-uncompress",
                                        "async",
                                        "auto-template",
                                        "bd-vif",
                                        "bdi",
                                        "bvi",
                                        "bluetooth",
                                        "cdma-ix",
                                        "cem-acr",
                                        "cem-pg",
                                        "ctunnel",
                                        "container",
                                        "dialer",
                                        "esconphy",
                                        "ethernet-internal",
                                        "fcpa",
                                        "filter",
                                        "filtergroup",
                                        "gmpls",
                                        "gigabitethernet",
                                        "group-async",
                                        "ima-acr",
                                        "lisp",
                                        "longreachethernet",
                                        "loopback",
                                        "lspvif",
                                        "mfr",
                                        "multilink",
                                        "nvi",
                                        "null_interface",
                                        "overlay",
                                        "protection_group",
                                        "port-channel",
                                        "portgroup",
                                        "pos-channel",
                                        "sbc",
                                        "sdh_acr",
                                        "serial-acr",
                                        "sonet_acr",
                                        "sslvpn-vif",
                                        "sysclock",
                                        "serial-pg",
                                        "service-engine",
                                        "tls-vif",
                                        "tunnel",
                                        "tunnel-tp",
                                        "vpn",
                                        "vif",
                                        "vir-cem-acr",
                                        "virtual-ppp",
                                        "virtual-template",
                                        "virtual-tokenring",
                                        "virtualportgroup",
                                        "vlan",
                                        "multiservice",
                                        "nve",
                                        "ucse",
                                        "vasileft",
                                        "vasiright",
                                        "vmi",
                                        "voabypassin",
                                        "voabypassout",
                                        "voafilterin",
                                        "voafilterout",
                                        "voain",
                                        "voaout",
                                    ],
                                },
                                "interface_number": {
                                    "type": "int",
                                    "required": True,
                                },
                            },
                        },
                        "ip_precedence": {"type": "list", "elements": "int"},
                        "ip_rtp": {
                            "type": "dict",
                            "options": {
                                "starting_port_number": {
                                    "type": "int",
                                    "required": True,
                                },
                                "port_range": {"type": "int", "required": True},
                            },
                        },
                        "metadata": {
                            "type": "dict",
                            "mutually_exclusive": [
                                [
                                    "cac_status",
                                    "called_uri",
                                    "caller_uri",
                                    "device_model",
                                    "global_session_id",
                                    "multi_party_session_id",
                                ]
                            ],
                            "options": {
                                "called_uri": {"type": "str"},
                                "calling_uri": {"type": "str"},
                                "device_model": {"type": "str"},
                                "global_session_id": {"type": "str"},
                                "multi_party_session_id": {"type": "str"},
                            },
                        },
                        "mpls_experimental_topmost": {
                            "type": "list",
                            "elements": "int",
                        },
                        "packet_length": {
                            "type": "dict",
                            "options": {
                                "max": {"type": "int"},
                                "min": {"type": "int"},
                            },
                        },
                        "protocol": {
                            "type": "dict",
                            "options": {
                                "protocol_name": {"required": True, "type": "str"},
                                "subprotocol_parameter": {
                                    "required_together": [
                                        [
                                            "subprotocol_parameter_name",
                                            "subprotocol_parameter_value",
                                        ]
                                    ],
                                    "type": "dict",
                                    "options": {
                                        "subprotocol_parameter_name": {
                                            "type": "str"
                                        },
                                        "subprotocol_parameter_value": {
                                            "type": "str"
                                        },
                                    },
                                },
                            },
                        },
                        "protocol_attribute": {
                            "type": "dict",
                            "options": {
                                "attribute_name": {
                                    "required": True,
                                    "type": "str",
                                },
                                "attribute_value": {
                                    "required": True,
                                    "type": "str",
                                },
                            },
                        },
                        "qos_group": {"type": "int"},
                        "security_group": {
                            "type": "dict",
                            "mutually_exclusive": [
                                ["source_tag", "destination_tag"]
                            ],
                            "options": {
                                "source_tag": {"type": "int"},
                                "destination_tag": {"type": "int"},
                            },
                        },
                        "source_mac_address": {"type": "str"},
                        "start": {
                            "type": "dict",
                            "mutually_exclusive": [
                                ["eq", "neq", "gt", "lt", "range", "regex"]
                            ],
                            "options": {
                                "layer": {
                                    "type": "str",
                                    "required": True,
                                    "choices": ["l2", "l3"],
                                },
                                "offset": {"type": "int", "required": True},
                                "size": {"type": "int", "required": True},
                                "eq": {
                                    "type": "dict",
                                    "options": {
                                        "value": {"type": "int", "required": True},
                                        "mask": {"type": "int"},
                                    },
                                },
                                "neq": {
                                    "type": "dict",
                                    "options": {
                                        "value": {"type": "int", "required": True},
                                        "mask": {"type": "int"},
                                    },
                                },
                                "gt": {"type": "int"},
                                "lt": {"type": "int"},
                                "range": {"type": "dict"},
                                "regex": {"type": "str"},
                            },
                        },
                        "traffic_category": {
                            "type": "str",
                            "choices": ["allow", "optimize"],
                        },
                        "vlan_id": {"type": "int"},
                        "vlan_id_inner": {"type": "int"},
                        "negate": {"type": "bool"},
                    },
                },
            },
        },
        "state": {
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
            "type": "str",
        },
    }  # pylint: disable=C0301
